services:
  - type: web
    name: cv-resume-integration
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn resume_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
